var data = {
    docSummary:[
        {
            _id:'234567',
            docTitle:"docTitle",
            tags:2,
            type:4
        },
        {
            _id:'334567',
            docTitle:"docTitle",
            tags:2,
            type:4
        },
        {
            _id:'434567',
            docTitle:"docTitle",
            tags:2,
            type:4
        }
    ],
    courseSummary:[
        {
            _id:'a2asd',
            courseName:"courseName",
            term:3,
            teacherName:"teacher"
        },
        {
            _id:'a2asd',
            courseName:"courseName",
            term:3,
            teacherName:"teacher"
        },
        {
            _id:'a2asd',
            courseName:"courseName",
            term:3,
            teacherName:"teacher"
        }
    ],
    lessonSummary:[
        {
            _id:'asf2342',
            lessonTitle:'lessonTitle',
            summary:'lessonSummary'
        },
        {
            _id:'asf2342',
            lessonTitle:'lessonTitle',
            summary:'lessonSummary'
        },
        {
            _id:'asf2342',
            lessonTitle:'lessonTitle',
            summary:'lessonSummary'
        }
    ],
    saveReslult:{
        result:"success/fail",
        Message:"fail message"
    },
    doc:{
        _id:"asdf3234",
        docTitle:"docTitle",
        content:'',
        type:'1',
        shareType:'2',
        tags:'23',
        lesson:{
            _id:'asdf',
            lessonTitle:'lessonTitle',
            summary:'lessonSummary'
        },
        course:{
            _id:'a2asd',
            courseName:"courseName",
            term:3
        },
        docOwner:{
            _id:"asdf",
            userType:'2',
            userName:"name",
            accountNumber:'123424'
        }
    }
}
module.exports = data;